name: "Action Item"
description: "This is an issue to update an action item"
title: "[AI] "
type: "Action Item"
# assignees: 
#   - "shawnalpay"
#   - "jpradocueva"
body:
  - type: markdown
    attributes:
      value: |
        ## Action Item Details

  - type: textarea
    id: details
    attributes:
      label: "Detailed Description"
      description: "Provide a detailed explanation of the action item, including context and any required steps."
      placeholder: "Explain why this action is needed and any dependencies."
    validations:
      required: false

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: "Describe what must be completed in order for this action item to be closed."
      placeholder: "A description of what must be completed in order for this action item to be closed."
    validations:
      required: true
