name: Feature Request and Use Case Feedback
description: Provide feedback on use cases or feature requests that cannot be performed with the current FOCUS specification. These may include FinOps-specific scenarios or other areas where the specification falls short. Your input will help prioritize improvements for upcoming releases. Please avoid sharing any information that may be considered Intellectual Property by any individual or organization.
title: "[FEEDBACK]: "
labels: ["use case"]
assignees: ["salpaysenturus, udam-f2, jpradocueva,"]
body:
  - type: markdown
    attributes:
      value: "The FOCUS working group aims to identify gaps in the current specification, both for FinOps-related use cases and broader areas. We are interested in understanding which use cases or features cannot be supported by the current specification so they can be prioritized for future releases. Please do not include any information that may be regarded as Intellectual Property."
  
  - type: input
    attributes:
      label: Proposed Change
      description: Short description of the change and why it is necessary.
      placeholder: Describe the proposed change briefly and why it is necessary
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: What use cases, FinOps or others, can't be performed with the current specification without this change?
      description: Describe in detail the use cases, whether FinOps-related or otherwise, that your organization cannot perform with the current specification without the proposed change.
    validations:
      required: true

  - type: input
    attributes:
      label: Which FinOps personas perform this use case?
      description: List one or more FinOps personas that perform this use case
      placeholder: e.g., Cost Analyst, Cloud Architect, etc
    validations:
      required: true

  - type: input
    attributes:
      label: For which providers do you perform this use case for?
      description: List each provider separated by commas
      placeholder: e.g., AWS, Azure, GCP, Snowflake, etc
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Criticality Scale
      description: On a scale of 1 - 4, how critical is this for your organization?
      options:
        - '1: Blocks my organization from adopting FOCUS'
        - '2: Important for adoption in the next 3-6 months'
        - '3: Important for adoption in the next 6-12 months'
        - '4: Suggestion, not planning to use FOCUS soon'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Business and Financial Objectives
      description: Describe the business and financial objectives this use case aims to achieve.
      placeholder: Describe the expected business and financial outcomes.
    validations:
      required: false

  - type: input
    attributes:
      label: Cost Drivers
      description: Identify the primary cost drivers related to this use case (e.g., cloud spending, infrastructure costs).
      placeholder: e.g., cloud spending, infrastructure costs, etc.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Key Metrics and KPIs
      description: List the metrics and KPIs that will measure the success of this use case (e.g., cost per service, spend reduction percentage).
      placeholder: e.g., cost per service, spend reduction percentage, etc.
    validations:
      required: false

  - type: input
    attributes:
      label: Expected Financial Impact
      description: Quantify the expected financial impact, if applicable (e.g., percentage cost savings, budget reductions).
      placeholder: e.g., 10% cost savings, 5% budget reduction, etc.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Testing Approach
      description: Outline how the use case will be tested before full implementation. Specify the types of testing (e.g., pilot testing, A/B testing).
      placeholder: Describe your testing approach.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Validation Criteria
      description: Define how success will be validated after implementation. Include metrics that will be reviewed post-implementation.
      placeholder: e.g., metrics to validate success, financial impact, etc.
    validations:
      required: false


  - type: textarea
    attributes:
      label: Context / Supporting information
      description: Provide any other relevant information here
      placeholder: Additional details...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Data Submission for Discussion
      description: Provide relevant sample data or data extracts that support your feedback. Ensure data is anonymized and does not include sensitive or proprietary information.
      placeholder: Attach sample data or data extracts here. Ensure compliance with data privacy guidelines.
    validations:
      required: true  

