name: "General Feedback"
description: Suggest minor corrections, clarity improvements, or inconsistencies in the FOCUS Specification.
title: "[Feedback] <Brief description of issue>"
labels: ["feedback", "needs triage"]
assignees: ["matt-cowsert"]
body:
  - type: markdown
    attributes:
      value: |
        _Use this form to report small corrections or suggestions that improve clarity, accuracy, or consistency._

        ⚠️ **Feature-related suggestions should be submitted via the Feature Request template instead.**

  - type: input
    id: organization
    attributes:
      label: Submitting Organization (Optional)
      description: If submitting on behalf of a company, enter it here.
      placeholder: e.g., BigCloud Inc.
    validations:
      required: false

  - type: textarea
    id: feedback_summary
    attributes:
      label: Feedback Summary
      description: Be specific and actionable.
      placeholder: e.g., Typo in field `skuDescription` — should say "metered" instead of "metred".
    validations:
      required: true

  - type: checkboxes
    id: feedback_type
    attributes:
      label: Type of Feedback
      description: Select the option that best describes your suggestion.
      options:
        - label: Typo or grammar
        - label: Clarity improvement
        - label: Field naming or label inconsistency
        - label: Definition or behavior inconsistency
        - label: Minor correction (non-breaking)
        - label: Other

  - type: input
    id: affected_section
    attributes:
      label: Affected Section or Field (Optional)
      placeholder: e.g., /definitions/UsageRecord or spec.md#sku-capacity
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes (Optional)
      description: Add any extra context, examples, or links here.
      placeholder: Anything else worth sharing?
    validations:
      required: false
