name: "Feature Request and Use Case Feedback"
description: "Provide feedback on unsupported FinOps features, use cases, or scenarios, as well as on the existing FOCUS specification content. Avoid sharing proprietary information."
title: "[FEEDBACK]: "
labels:
  - "feedback"
assignees:
  - "shawnalpay"
  - "jpradocueva"
body:
  - type: markdown
    attributes:
      value: |
        ---
        ### **Template Usage Notes**:
        1. All fields marked as **mandatory** [*] must be filled before submission.
        2. For **Supporting Data/Documentation**, ensure that linked files are accessible to relevant stakeholders.
        3. If you wish to file a bug report using the markdown version of this issue template, please click [here](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/new?template=feedback.md)


  - type: markdown
    attributes:
      value: |
        ## 1. **Problem statement**
        Describe the problem or opportunity that this issue addresses. Explain the context and why it needs resolution.

  - type: textarea
    id: issue-summary
    attributes:
      label: Summary
      description: "Briefly describe the problem or opportunity that this issue addresses and why it needs resolution."
      placeholder: "Briefly describe the problem or opportunity that needs resolution."
    validations:
      required: true

  - type: dropdown
    id: issue-area
    attributes:
      label: Which area does this issue relate to?
      description: "Select one of the provided options:"
      options:
        - 'A: Missing FinOps feature, use case, or scenario'
        - 'B: Existing FOCUS specification content'
        - 'C: Other'
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Detailed Description
      description: "Provide a detailed description of the problem or opportunity. Add context or any other relevant information that may help in addressing this issue."
      placeholder: "Provide a comprehensive description of the the problem or opportunity, including context and any relevant details"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 2. **Use Cases**
        Please describe the use cases, whether FinOps-related or otherwise, that cannot be performed with the existing specification unless this issue is addressed.

  - type: textarea
    id: use_cases
    attributes:
      label: What use cases, FinOps or others, can't be performed with the existing specification unless this issue is addressed?
      description: "Provide detailed descriptions of the use cases that can't be performed unless this issue is addressed."
      placeholder: "List the specific use cases that can't be performed due to the existing limitations."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 3. **FinOps Personas**
        List the FinOps personas this issue relates to.

  - type: textarea
    id: finops-personas
    attributes:
      label: Which FinOps personas does this issue relate to?
      description: "Indicate which FinOps personas this issue relates to."
      placeholder: "e.g., Practitioner, Executive, Finance, Engineering, Procurement, Operations, etc."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 4. **Providers**
        List provider groups or specific providers this issue relates to.

  - type: textarea
    id: providers
    attributes:
      label: Which provider groups or specific providers does this issue relate to?
      description: "List provider groups (e.g., CSPs, SaaS) separated by semicolons (`;`), and specific providers within those groups separated by commas (`,`). If the issue applies to all providers within a group, you can simply specify the group name (e.g., 'All CSPs')."
      placeholder: "e.g., All CSPs; SaaS: Snowflake, Salesforce"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 5. **Criticality Scale**
        Indicate how critical this issue or feature request is for your organization using the scale provided below.

  - type: dropdown
    id: criticality-scale
    attributes:
      label: On a scale of 1 - 4, how critical is this for your organization? 
      description: "Select one of the provided options."
      options:
        - '1: Blocks my organization from adopting FOCUS'
        - '2: Important for adoption in the next 3-6 months'
        - '3: Important for adoption in the next 6-12 months'
        - '4: Suggestion, not planning to use FOCUS soon'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 6. **Objective**
        State the objective of this feedback. 
        - What outcome is expected?
        - Define how success will be measured (e.g., metrics and KPIs).

  - type: textarea
    id: objective
    attributes:
      label: "Objective"
      description: "Outline the expected outcome and success criteria."
      placeholder: "Outline the desired outcome and any metrics or KPIs to measure success."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 7. **Supporting Data/Documentation**

  - type: textarea
    id: data_examples
    attributes:
      label: "Data Examples"
      description: "Provide links to relevant sample data or attach data extracts that support your feedback. Ensure data is anonymized and does not include sensitive or proprietary information."
      placeholder: "Add link(s) to sample data or attach extracts that support your feedback."
    validations:
      required: false

  - type: textarea
    id: issue_pr_references
    attributes:
      label: "Issues, PRs, or Other References"
      description: "Provide links to any relevant GitHub issues, pull requests, or other applicable references."
      placeholder: "Add links to any relevant GitHub issues, pull requests, or other applicable references."
    validations:
      required: false
