name: "Feature Request and Use Case Feedback"
description: "Provide feedback on unsupported FinOps features, use cases, or scenarios, as well as on the current FOCUS specification content or FOCUS datasets. Avoid sharing proprietary information."
title: "[FEEDBACK]: "
labels:
  - "feedback"
assignees:
  - "shawnalpay"
  - "jpradocueva"
body:
  - type: markdown
    attributes:
      value: "Provide feedback on unsupported FinOps features, use cases, or scenarios, as well as on the current FOCUS specification content or FOCUS datasets. Avoid sharing proprietary information."

  - type: markdown
    attributes:
      value: |
        ## 1. Issue area
        Select the the area(s) this issue relates to

  - type: dropdown
    id: issue-area
    attributes:
      label: "Indicate which area this issue relates to:"
      options:
        - 'Missing FinOps feature, use case, or scenario'
        - 'Current FOCUS specification content'
        - 'Produced FOCUS dataset'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 2. Proposed Change
        Please provide a short description of the change and explain why it is necessary.

  - type: textarea
    attributes:
      label: Proposed Change
      description: "Describe the proposed change briefly and explain its necessity."
      placeholder: "Your input here..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Use Cases Impacted
        Please describe the use cases, whether FinOps-related or otherwise, that cannot be performed with the current specification without the proposed change.

  - type: textarea
    id: impacted_use_cases
    attributes:
      label: What use cases, FinOps or others, can't be performed with the current specification without this change?
      description: "Provide detailed descriptions of the use cases that can't be performed due to the current limitations."
      placeholder: "Your input here..."
    validations:
      required: true

  - type: textarea
    id: supporting_information
    attributes:
      label: Context / Supporting Information
      description: "Provide any other relevant information here."
      placeholder: "Your input here..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 3. FinOps Personas
        Below is a list of FinOps personas. Please check all that apply.

  - type: dropdown
    id: finops-personas
    attributes:
      label: Which the FinOps personas this issue relates to?
      description: Indicate which FinOps Personas this issue relates to (you may select more than one, if applicable).
      options:
        - label: Practitioner
          value: practitioner
        - label: Executive
          value: executive
        - label: Finance
          value: finance
        - label: Engineering
          value: engineering
        - label: Product
          value: product
        - label: Procurement
          value: procurement
        - label: Operations
          value: operations
        - label: Other (please specify below)
          value: other
    validations:
      required: true

  - type: input
    id: other-finops-persona
    attributes:
      label: If 'Other', please specify FinOps personas
      description: "Leave this field empty if you did not select 'Other'."
      placeholder: "Your input here..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 4. Providers
        Select the Providers this issue relates to

  - type: dropdown
    id: providers
    attributes:
      label: Indicate which Providers this issue relates to
      options:
        - label: AWS
          value: AWS
        - label: GCP
          value: GCP
        - label: Microsoft
          value: Microsoft
        - label: OCI 
          value: OCI        
        - label: Other (please specify below)
          value: other
    validations:
      required: true

  - type: input
    id: other-provider
    attributes:
      label: If 'Other', please specify the provider
      description: "Leave this field empty if you did not select 'Other'."
      placeholder: "Your input here..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 5. Criticality Scale
        Please indicate how critical this issue or feature request is for your organization using the scale provided below.

  - type: dropdown
    id: criticality-scale
    attributes:
      label: Criticality Scale
      description: On a scale of 1 - 4, how critical is this for your organization?
      options:
        - label: '1: Blocks my organization from adopting FOCUS'
          value: 1
        - label: '2: Important for adoption in the next 3-6 months'
          value: 2
        - label: '3: Important for adoption in the next 6-12 months'
          value: 3
        - label: '4: Suggestion'
          value: 4
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Objective
        State the objective of this work item. What outcome is expected?
        - **Success Criteria**: Define how success will be measured (e.g. metrics and KPIs).

  - type: textarea
    id: objective
    attributes:
      label: "Objective"
      description: "Describe the expected outcome and success criteria."
      placeholder: "Your input here..."
      value: "Outline the expected outcome and success criteria."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 6. Supporting Documentation
        - Data Examples: [Attach relevant sample data or provide links; DO NOT share proprietary information]
        - PRs or Other References: [Provide links to relevant references]

  - type: textarea
    id: supporting_documentation
    attributes:
      label: "Supporting Documentation"
      description: "Attach or provide links to relevant sample data or data extracts. If available, also provide links to existing PRs or other relevant documents. Ensure data is anonymized and does not include sensitive or proprietary information."
      placeholder: "Your input here..."
    validations:
      required: false