name: Spec Change
description: Submit changes or updates to the current specification.
title: "[SPEC CHANGE]: "
labels: ["discussion topic"]
assignees: ["mike-finopsorg,udam-f2"]
body:
  - type: dropdown
    attributes:
      label: Type of Issue
      description: Select the type of spec change (e.g., Dimension, Metric, Attribute, Documentation).
      options:
        - 'Dimension'
        - 'Metric'
        - 'Attribute'
        - 'Documentation'
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Normalized
      description: Indicate if the dimension is normalized.
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the issue and the changes being proposed.
      placeholder: Provide a detailed description of the spec change.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Definition of Done
      description: Checklist of items that define the completion of the spec change.
      placeholder: "- Rationalize vendor-neutral, cross-cloud naming\n- Complete spec template and include naming, constraints, guidelines\n- Include principles and governance criteria for maintaining normalized dimensions"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context / Supporting Information
      description: Provide any additional context that may help in understanding or evaluating the spec change. Include mappings between normalized values and vendor-specified values if applicable.
      placeholder: Additional context, references to other issues, or any relevant supporting information.
    validations:
      required: false
