name: "Work Item Issue Template"
description: "Template for creating new work item issues"
title: "[Work_Item]"
labels: 
  - "work item"
assignees: 
  - "shawnalpay"
  - "jpradocueva"
body:
  - type: markdown
    attributes:
      value: |
        ## 1. **Problem Statement**
        Describe the problem, issue, use case, or opportunity that this work item addresses.
        - **What is the problem?**: Explain the context and why it needs resolution.
        - **Impact**: Describe how the problem affects users, systems, or the project.

  - type: textarea
    id: problem_statement
    attributes:
      label: "Problem Statement"
      description: "Provide a detailed explanation of the problem or issue."
      placeholder: "Your input here..."
      value: "Provide details of the problem statement here."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 2. **Objective**
        State the objective of this work item. What outcome is expected?
        - **Success Criteria**: Define how success will be measured (e.g., columns, KPIs, metrics, content).

  - type: textarea
    id: objective
    attributes:
      label: "Objective"
      description: "Describe the expected outcome and success criteria."
      placeholder: "Your input here..."
      value: "Outline the expected outcome and success criteria."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 3. **Supporting Documentation**
        Include links to supporting documents such as:
        - Data Examples: [Link to data or relevant files]
        - Related Use Cases or Discussion Documents: [Link to discussion]
        - PRs or Other References: [Link to relevant references]

  - type: textarea
    id: supporting_documentation
    attributes:
      label: "Supporting Documentation"
      description: "Provide links to data examples, use cases, PRs, or other relevant documents."
      placeholder: "Your input here..."
      value: "Include links to supporting documentation, if applicable."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 4. **Proposed Solution / Approach**
        Outline any proposed solutions, approaches, or potential paths forward.
        - **Initial Ideas**: Describe potential solution paths, tools, or technologies.
        - **Considerations**: Include any constraints, dependencies, or risks.

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution / Approach"
      description: "Outline potential solutions or approaches."
      placeholder: "Your input here..."
      value: "Summarize the proposed solution or approach."

  - type: markdown
    attributes:
      value: |
        ## 5. **Epic or Theme Association**
        > This section will be completed by the Maintainers.
        > - **Epic**: [Epic Name]
        > - **Theme**: [Theme Name, if applicable]

  - type: textarea
    id: epic_theme
    attributes:
      label: "Epic or Theme Association"
      description: "Provide potential epics or themes"
      placeholder: "Your input here..."
      value: "Provide the rational for the Epic or Theme."

  - type: markdown
    attributes:
      value: |
        ## 6. **Stakeholders**
        List the main stakeholders for this issue.
        - **Primary Stakeholder**: [Name/Role]
        - **Other Involved Parties**: [Names/Roles]

  - type: textarea
    id: stakeholders
    attributes:
      label: "Stakeholders"
      description: "List the main stakeholders for this work item."
      placeholder: "Your input here..."
      value: "Provide names and roles of key stakeholders."

  - type: markdown
    attributes:
      value: |
        ---
        ### **Template Usage Notes**:
        1. All fields marked as **mandatory** [*] must be filled before submission.
        2. For **Supporting Documentation**, ensure that linked files are accessible to relevant stakeholders.