Conformance Requirements – `Column Handling`

text: [ColumnHandling_v1_2](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/v1.2/specification/attributes/column_handling.md)

| CRID                   | Function  | Reference       | Keyword    | ApplicabilityCriteria | Condition                                               | MustSatisfy                                                                                                                                                                               | Requirement                                                                                                                                                                                         | Type   | CRVersionIntroduced | Status | Notes          |
| ---------------------- | --------- | --------------- | ---------- | --------------------- | ------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ | ------------------- | ------ | -------------- |
| ColumnHandling-A-000-M | Composite | Column Handling | —          | All Rows              | All Rows                                                | All columns defined in the FOCUS specification MUST follow the naming and ordering requirements listed below.                                                                             | AND(ColumnHandling-A-001-M, ColumnHandling-A-010-M, ColumnHandling-A-013-O, ColumnHandling-A-019-M, ColumnHandling-A-020-M)                                                                         | static | 1.2                 | active | Root composite |
| ColumnHandling-A-001-M | Composite | Column Handling | MUST       | All Rows              | All Rows                                                | All columns defined by FOCUS MUST follow the following rules:                                                                                                                             | AND(ColumnHandling-A-002-M, ColumnHandling-A-003-M, ColumnHandling-A-004-M, ColumnHandling-A-005-O, ColumnHandling-A-006-O, ColumnHandling-A-007-M, ColumnHandling-A-008-C, ColumnHandling-A-009-M) | static | 1.2                 | active | —              |
| ColumnHandling-A-002-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Column IDs MUST use Pascal case.                                                                                                                                                          | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-003-M | Format    | Column Handling | MUST NOT   | All Rows              | All Rows                                                | Column IDs MUST NOT use abbreviations.                                                                                                                                                    | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-004-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Column IDs MUST be alphanumeric with no special characters.                                                                                                                               | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-005-O | Format    | Column Handling | SHOULD NOT | All Rows              | All Rows                                                | Column IDs SHOULD NOT use acronyms.                                                                                                                                                       | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-006-O | Format    | Column Handling | SHOULD NOT | All Rows              | All Rows                                                | Column IDs SHOULD NOT exceed 50 characters to accommodate column length restrictions of various data repositories.                                                                        | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-007-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Columns that have an ID and a Name MUST have the `Id` or `Name` suffix in the Column ID.                                                                                                  | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-008-C | Format    | Column Handling | MAY        | All Rows              | if there are no other columns with the same name prefix | Column display names MAY avoid the `Name` suffix if there are no other columns with the same name prefix.                                                                                 | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-009-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Columns with the `Category` suffix MUST be normalized.                                                                                                                                    | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-010-M | Composite | Column Handling | MUST       | All Rows              | All Rows                                                | Custom (e.g., provider-defined) columns that are not defined by FOCUS but included in a *FOCUS dataset* MUST follow the following rules:                                                  | AND(ColumnHandling-A-011-M, ColumnHandling-A-012-O)                                                                                                                                                 | static | 1.2                 | active | —              |
| ColumnHandling-A-011-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Custom columns MUST be prefixed with a consistent `x_` prefix to identify them as external, custom columns and distinguish them from FOCUS columns to avoid conflicts in future releases. | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-012-O | Format    | Column Handling | SHOULD     | All Rows              | All Rows                                                | Custom columns SHOULD follow the same rules listed above for FOCUS columns.                                                                                                               | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-013-O | Composite | Column Handling | SHOULD     | All Rows              | All Rows                                                | Column Order:                                                                                                                                                                             | AND(ColumnHandling-A-014-O, ColumnHandling-A-015-O, ColumnHandling-A-016-O, ColumnHandling-A-017-O, ColumnHandling-A-018-O)                                                                         | static | 1.2                 | active | —              |
| ColumnHandling-A-014-O | Order     | Column Handling | SHOULD     | All Rows              | All Rows                                                | All FOCUS columns SHOULD be first in the provided dataset.                                                                                                                                | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-015-O | Order     | Column Handling | SHOULD     | All Rows              | All Rows                                                | Custom columns SHOULD be listed after all FOCUS columns.                                                                                                                                  | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-016-O | Order     | Column Handling | SHOULD NOT | All Rows              | All Rows                                                | Custom columns SHOULD NOT be intermixed.                                                                                                                                                  | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-017-O | Order     | Column Handling | MAY        | All Rows              | All Rows                                                | Columns MAY be sorted alphabetically.                                                                                                                                                     | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-018-O | Order     | Column Handling | SHOULD     | All Rows              | All Rows                                                | Custom columns SHOULD be after all FOCUS columns.                                                                                                                                         | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-019-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Exceptions: Identifiers will use the "Id" abbreviation since this is a standard pattern across the industry.                                                                              | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
| ColumnHandling-A-020-M | Format    | Column Handling | MUST       | All Rows              | All Rows                                                | Exceptions: Product offerings that incur charges will use the "Sku" abbreviation because it is a well-understood term both within and outside the industry.                               | null                                                                                                                                                                                                | static | 1.2                 | active | —              |
