# Fun features (e.g., generating a poem about the PR)
have_fun: true

# Settings for the Persistent Memory feature
memory_config:
  disabled: false

# Global code review behavior
code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: -1
  
  pull_request_opened:
    help: false
    summary: true
    code_review: false
    include_drafts: true